### ISSUE TITLE
No screeninit = black screen

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#26]
So, apparently, Corbenik no longer works if using noscreeinit A9LH / Using AuroraWright's A9LH with arm9loaderhax.bin (no screen init) and just black screens.

**Comment by chaoskagami** [comment]
Strange. I need sleep, so if you can do a little testing for me and report back, I'd appreciate it.

Go here: https://github.com/chaoskagami/corbenik/blob/master/source/screeninit.c#L27

Replace that line with: `i2cWriteRegister(I2C_DEV_MCU, 0x22, 0x2A);`

Test and see if that works. That's how the code was previously.

**Comment by gnmmarechal** [comment]
I will, good night.

**Comment by gnmmarechal** [comment]
Hum, compilation error.

![](https://i.gyazo.com/40f76b8c1c9de58b5ef2bf1294776007.png)

**Comment by chaoskagami** [comment]
This has been fixed in my local branch, so next push will contain this and other assorted fixes. I'll close it then.

**Comment by gnmmarechal** [comment]
All right, cool :)

**Comment by chaoskagami** [comment]
Fixed by https://github.com/chaoskagami/corbenik/commit/3519ba0d082e73ff3f82c8e839bd05450f7a869b (amongst other changes)

**Comment by Plailect** [comment]
I still encounter this issue, but not 100% of the time.

Using arm9loaderhax_si.bin works just fine.

**Comment by chaoskagami** [comment]
It looks like this is potentially aggravated by AW's branch, but I'm unsure why. Either way, I have to reopen this and figure out why now. _sigh_

**Comment by chaoskagami** [comment]
https://github.com/chaoskagami/corbenik/commit/8e0ebc1b35f04fdea09bf8de4f1f5acdb3ad07d0 should fix both this and #29. If anyone can test the latest nightly build and confirm this is the case, I'd be rather happy.

Still will be refactored whenever libctr11 comes around, oh well.

Closing unless I need to reopen it.
